name: Auto Sync Fork (Hourly)

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # 必须要有写入权限
    steps:
      # 1. 检出当前仓库（必须使用持久化参数）
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # 关键！必须获取完整历史记录
          persist-credentials: true  # 保持认证信息

      # 3. 同步上游仓库
      - name: Sync with upstream
        uses: aormsby/Fork-Sync-With-Upstream-action@v3.4.1
        with:
          upstream_repository: "mogworks/xivstrat"
          upstream_branch: "main"
          target_branch: "main"
          git_pull_args: "--ff-only"
          git_push_args: "--force-with-lease"

      # 4. 可选通知
      - name: Notify if updated
        if: success()
        run: echo "Fork synced successfully!"
