name: Auto Sync Fork (Hourly)

on:
  schedule:
    - cron: '0 * * * *'  # 每个小时的第 0 分钟运行
  workflow_dispatch:     # 允许手动点击运行

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      # 新增：检出你的仓库
      - name: Checkout current fork
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # 拉取完整历史记录（必要！）

      # 原有同步步骤
      - name: Sync with upstream
        uses: aormsby/Fork-Sync-With-Upstream-action@v3.4.1
        with:
          upstream_repository: "mogworks/xivstrat"
          upstream_branch: "main"
          target_branch: "main"
          git_pull_args: "--ff-only"
          git_push_args: "--force-with-lease"

